### ISSUE TITLE
Remove Chrome warning from README

### ISSUE THREAD

**Issue by meyerweb** [runarberg/mathup#66]
This bit:

```
 And you should probably use it
*along side* this package as well if you want
[Chrome users](http://www.chromestatus.com/features/5240822173794304)
to be able to read your expressions.
```

…can be removed from the README at some point in the near future, as Chrome has comprehensive MathML Core support as of Chrome 109.

**Comment by runarberg** [comment]
You are right... And I can probably remove the passive aggressive tone from this section as well 😛. Perhaps it is time to go back to maintaining this library now that there is complete browser support.

**Comment by runarberg** [comment]
README updated. Thanks for the ping.
