### ISSUE TITLE
∧ displays as superscript when after an index

### ISSUE THREAD

**Issue by xlf1024** [runarberg/mathup#9]
`u ^^` works correctly, displays as "u∧"
`u_1 ^^` ignores the space between `1` and `^^`, thus places the ∧ as superscript. 

(Optically correct result can be optained here with `{:u_1:} ^^` or `u_1 ∧`.)

**Comment by xlf1024** [comment]
_(sorry for spamming issues)_

**Comment by runarberg** [comment]
@xlf1024 This will be fixed in the next major version (named *“mathup”*) which is a complete rewrite of the internals.

**Comment by xlf1024** [comment]
Thank you!
